//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountprofile
    {
        public long Id { get; set; }
        public System.DateTime Created_at { get; set; }
        public bool AccountStatus { get; set; }
        public float TotCreditAvail { get; set; }
        public float ServiceNumber { get; set; }
        public System.DateTime PlanExpDate { get; set; }
        public long UserId { get; set; }
        public long PlanId { get; set; }
    }
}
