//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_logs
    {
        public string input { get; set; }
        public string output { get; set; }
        public string data { get; set; }
        public int id { get; set; }
        public System.DateTime date { get; set; }
    }
}
