//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bundle_tarrif
    {
        public int Id { get; set; }
        public Nullable<long> bundle_id { get; set; }
        public string bundle_rate_per_plan { get; set; }
    }
}
