//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bundleprice
    {
        public long Id { get; set; }
        public System.DateTime Created_at { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public long BundleId { get; set; }
        public string size { get; set; }
        public string ExpDate { get; set; }
    }
}
