//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_care_comments
    {
        public long id { get; set; }
        public long reg_id { get; set; }
        public string comments { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime modified_on { get; set; }
    }
}
