//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datacard_bundles
    {
        public long id { get; set; }
        public long plan_id { get; set; }
        public string name { get; set; }
        public string account_type { get; set; }
        public string Size { get; set; }
    }
}
