//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class denomination_type
    {
        public long Id { get; set; }
        public string type { get; set; }
        public long plan_id { get; set; }
        public Nullable<long> unit { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
