//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class multiplesim
    {
        public long Id { get; set; }
        public long RegistrationId { get; set; }
        public string MsisdnNumber { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string description { get; set; }
    }
}
