//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_denomination
    {
        public plan_denomination()
        {
            this.favorite_plans = new HashSet<favorite_plans>();
            this.plan_price = new HashSet<plan_price>();
        }
    
        public long id { get; set; }
        public long plan_id { get; set; }
        public string denomination { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<long> units { get; set; }
        public Nullable<long> denomination_type_id { get; set; }
        public Nullable<long> plan_type_id { get; set; }
    
        public virtual ICollection<favorite_plans> favorite_plans { get; set; }
        public virtual ICollection<plan_price> plan_price { get; set; }
        public virtual plan plan { get; set; }
    }
}
