//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan
    {
        public plan()
        {
            this.plan_denomination = new HashSet<plan_denomination>();
            this.plan_price = new HashSet<plan_price>();
        }
    
        public long Id { get; set; }
        public string name { get; set; }
        public long account_type { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> minmeasureid { get; set; }
        public Nullable<long> plan_type_id { get; set; }
    
        public virtual ICollection<plan_denomination> plan_denomination { get; set; }
        public virtual ICollection<plan_price> plan_price { get; set; }
    }
}
