//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_price
    {
        public long id { get; set; }
        public long plan_id { get; set; }
        public long denom_id { get; set; }
        public long price { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual plan_denomination plan_denomination { get; set; }
        public virtual plan plan { get; set; }
    }
}
