//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recharge_det
    {
        public int id { get; set; }
        public string RECHARGENUMBER { get; set; }
        public string RECHARGEAMOUNT { get; set; }
        public string RECHARGETIME { get; set; }
        public string ACCOUNTTYPE1 { get; set; }
        public string RECHARGETYPE { get; set; }
        public string RECHARGE { get; set; }
        public string VOUCHERCARDSEQ { get; set; }
        public string BALANCEAFTERRECHARGE { get; set; }
        public string ACTUALRECHARGEAMT { get; set; }
        public string FREEACCOUNTTYP { get; set; }
        public string BONUSBALAN { get; set; }
        public string CURRENTBAL { get; set; }
    }
}
