//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public registration()
        {
            this.favorite_plans = new HashSet<favorite_plans>();
            this.voucher_blocklist = new HashSet<voucher_blocklist>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string company { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string Email { get; set; }
        public string Parish { get; set; }
        public string HomeNumber { get; set; }
        public string MobileNumber { get; set; }
        public string MsisdnNumber { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<System.DateTime> Modified_on { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isSelfCare { get; set; }
        public string verification_code { get; set; }
        public string temppas { get; set; }
        public Nullable<System.DateTime> temppascreatedat { get; set; }
        public string encryptedid { get; set; }
        public string mobileverification { get; set; }
        public Nullable<bool> isShopping { get; set; }
        public string account_number { get; set; }
        public string mother_maiden_name { get; set; }
        public string favourite_colour { get; set; }
        public string pet_name { get; set; }
        public string FFNumber { get; set; }
        public Nullable<bool> isMobileAccess { get; set; }
    
        public virtual ICollection<favorite_plans> favorite_plans { get; set; }
        public virtual ICollection<voucher_blocklist> voucher_blocklist { get; set; }
    }
}
