//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bemobileselfcareEntities : DbContext
    {
        public bemobileselfcareEntities()
            : base("name=bemobileselfcareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountprofile> accountprofiles { get; set; }
        public DbSet<api_logs> api_logs { get; set; }
        public DbSet<application_transaction> application_transaction { get; set; }
        public DbSet<application_transaction_log> application_transaction_log { get; set; }
        public DbSet<bundle_tarrif> bundle_tarrif { get; set; }
        public DbSet<bundleprice> bundleprices { get; set; }
        public DbSet<bundle> bundles { get; set; }
        public DbSet<datacard_bundles> datacard_bundles { get; set; }
        public DbSet<denomination_type> denomination_type { get; set; }
        public DbSet<errormessage> errormessages { get; set; }
        public DbSet<favorite_plans> favorite_plans { get; set; }
        public DbSet<gprs_det> gprs_det { get; set; }
        public DbSet<mon_det> mon_det { get; set; }
        public DbSet<multiplesim> multiplesims { get; set; }
        public DbSet<plan_denomination> plan_denomination { get; set; }
        public DbSet<plan_price> plan_price { get; set; }
        public DbSet<plan_type> plan_type { get; set; }
        public DbSet<plandetail> plandetails { get; set; }
        public DbSet<plan> plans { get; set; }
        public DbSet<qlink> qlinks { get; set; }
        public DbSet<recharge_det> recharge_det { get; set; }
        public DbSet<recommend> recommends { get; set; }
        public DbSet<registration> registrations { get; set; }
        public DbSet<respons> responses { get; set; }
        public DbSet<service> services { get; set; }
        public DbSet<sim_activation> sim_activation { get; set; }
        public DbSet<simverificationcode> simverificationcodes { get; set; }
        public DbSet<sms_app_tx> sms_app_tx { get; set; }
        public DbSet<sms_det> sms_det { get; set; }
        public DbSet<sms_in_log> sms_in_log { get; set; }
        public DbSet<sms_out_log> sms_out_log { get; set; }
        public DbSet<smsout> smsouts { get; set; }
        public DbSet<topup_transactions> topup_transactions { get; set; }
        public DbSet<topupplan> topupplans { get; set; }
        public DbSet<transaction> transactions { get; set; }
        public DbSet<transfer_det> transfer_det { get; set; }
        public DbSet<userhistory> userhistories { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<validity> validities { get; set; }
        public DbSet<voice_det> voice_det { get; set; }
        public DbSet<voucher_blocklist> voucher_blocklist { get; set; }
        public DbSet<your_plan_transaction_denominations> your_plan_transaction_denominations { get; set; }
        public DbSet<your_plan_transactions> your_plan_transactions { get; set; }
    }
}
