//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public long Id { get; set; }
        public System.DateTime Created_at { get; set; }
        public string ServiceName { get; set; }
        public float SetupFee { get; set; }
        public float PerPeriodFee { get; set; }
        public string Compulsory { get; set; }
        public long planId { get; set; }
    }
}
