//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class simverificationcode
    {
        public long Id { get; set; }
        public string msisdn { get; set; }
        public string verificationcode { get; set; }
        public System.DateTime createdAt { get; set; }
    }
}
