//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_det
    {
        public int id { get; set; }
        public string CALLING_PARTY_NUMBER { get; set; }
        public string CALLED_PARTY_NUMBER { get; set; }
        public string SERVICEFLOW { get; set; }
        public string ACTUAL_USAGE { get; set; }
        public string USAGEFROMSMSBUNDLE { get; set; }
        public string CHARGEFROMPREPAID { get; set; }
        public string CHARGETIME { get; set; }
        public string CALLFORWARDI { get; set; }
        public string SMSTYPE { get; set; }
        public string ROAMSTATE { get; set; }
        public string CALLEDHOMENETWORKCOD { get; set; }
        public string ACCOUNTTYPE1 { get; set; }
        public string CURRENTBALANCEACNT1 { get; set; }
        public string FREEACCOUNTTYPE1 { get; set; }
        public string CURRENTBALANCEFREEACNT1 { get; set; }
        public string FREEACCOUNTTYPE2 { get; set; }
        public string CURRENTBALANCEFREEACNT2 { get; set; }
    }
}
