//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class topup_transactions
    {
        public long Id { get; set; }
        public string msisdn { get; set; }
        public long amount { get; set; }
        public string reference { get; set; }
        public string details { get; set; }
        public long reg_id { get; set; }
        public string status { get; set; }
    }
}
