//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class topupplan
    {
        public double Id { get; set; }
        public string Size { get; set; }
        public string Validity { get; set; }
        public double Price { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Name { get; set; }
    }
}
