//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer_det
    {
        public int id { get; set; }
        public string CHARGINGPARTYNUMBER { get; set; }
        public string TRANSFEREDAMOUNT { get; set; }
        public string HANDLINGFEE { get; set; }
        public string TRANSFERTIME { get; set; }
    }
}
