//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public long Id { get; set; }
        public long InvoiceNo { get; set; }
        public System.DateTime Created_at { get; set; }
        public System.DateTime BillDate { get; set; }
        public float CallUnits { get; set; }
        public float CallCharges { get; set; }
        public float DataUsage { get; set; }
        public float DataCharges { get; set; }
        public float MonthlyRent { get; set; }
        public float Total { get; set; }
        public bool PaidStatus { get; set; }
        public float PaidAmount { get; set; }
        public float Balance { get; set; }
        public long UserId { get; set; }
        public long PlanId { get; set; }
    }
}
