//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userhistory
    {
        public long id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public long PlanId { get; set; }
        public long UserId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string toMsisdn { get; set; }
        public Nullable<bool> isExpired { get; set; }
        public Nullable<bool> isTopup { get; set; }
    }
}
