//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voice_det
    {
        public int id { get; set; }
        public Nullable<System.DateTime> CALL_DATE { get; set; }
        public string CALLED_NUMBER { get; set; }
        public string CALLTYPE { get; set; }
        public string DURATION { get; set; }
        public string BALANCE_TYPE { get; set; }
        public string CHARGE_AMOUNT { get; set; }
        public string BALANCE_AFTER_CALL { get; set; }
        public string ACCOUNT_TYPE_ID_1 { get; set; }
        public string CHARGE_FROM_FREE_UNIT_1 { get; set; }
        public string BAL_OF_ACNT1_AFTER_CALL { get; set; }
        public string PLAN_NAME { get; set; }
    }
}
