//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher_blocklist
    {
        public long id { get; set; }
        public long user { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual registration registration { get; set; }
    }
}
