//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class your_plan_transactions
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string from_msisdn { get; set; }
        public string to_msisdn { get; set; }
        public Nullable<double> total_amt { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<bool> isExpired { get; set; }
    }
}
