//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.siCCBundleRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="siCCBundleRef.IBundlePlanSI")]
    public interface IBundlePlanSI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlanSI/CreateorEdit_BunldePlanSICc", ReplyAction="http://tempuri.org/IBundlePlanSI/CreateorEdit_BunldePlanSICcResponse")]
        string CreateorEdit_BunldePlanSICc(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlanSI/DeleteBunldePlanSICc", ReplyAction="http://tempuri.org/IBundlePlanSI/DeleteBunldePlanSICcResponse")]
        string DeleteBunldePlanSICc(string sUname, string sPwd, string sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBundlePlanSI/GetBundleType", ReplyAction="http://tempuri.org/IBundlePlanSI/GetBundleTypeResponse")]
        string GetBundleType(string sUname, string sPwd, string sData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBundlePlanSIChannel : si_bmobile.siCCBundleRef.IBundlePlanSI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BundlePlanSIClient : System.ServiceModel.ClientBase<si_bmobile.siCCBundleRef.IBundlePlanSI>, si_bmobile.siCCBundleRef.IBundlePlanSI {
        
        public BundlePlanSIClient() {
        }
        
        public BundlePlanSIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BundlePlanSIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BundlePlanSIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BundlePlanSIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateorEdit_BunldePlanSICc(string sUname, string sPwd, string sData) {
            return base.Channel.CreateorEdit_BunldePlanSICc(sUname, sPwd, sData);
        }
        
        public string DeleteBunldePlanSICc(string sUname, string sPwd, string sData) {
            return base.Channel.DeleteBunldePlanSICc(sUname, sPwd, sData);
        }
        
        public string GetBundleType(string sUname, string sPwd, string sData) {
            return base.Channel.GetBundleType(sUname, sPwd, sData);
        }
    }
}
