//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.esipayRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="esipayRef.IesipayService")]
    public interface IesipayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IesipayService/CheckCustomer", ReplyAction="http://tempuri.org/IesipayService/CheckCustomerResponse")]
        string CheckCustomer(string serUserName, string serPassword, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IesipayService/GetTokenNumber", ReplyAction="http://tempuri.org/IesipayService/GetTokenNumberResponse")]
        string GetTokenNumber(string serUserName, string serPassword, string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IesipayServiceChannel : si_bmobile.esipayRef.IesipayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IesipayServiceClient : System.ServiceModel.ClientBase<si_bmobile.esipayRef.IesipayService>, si_bmobile.esipayRef.IesipayService {
        
        public IesipayServiceClient() {
        }
        
        public IesipayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IesipayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IesipayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IesipayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckCustomer(string serUserName, string serPassword, string data) {
            return base.Channel.CheckCustomer(serUserName, serPassword, data);
        }
        
        public string GetTokenNumber(string serUserName, string serPassword, string data) {
            return base.Channel.GetTokenNumber(serUserName, serPassword, data);
        }
    }
}
