//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si_bmobile.dokuRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentEntModel", Namespace="http://schemas.datacontract.org/2004/07/doku_payment.Models")]
    [System.SerializableAttribute()]
    public partial class PaymentEntModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_freight_totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private si_bmobile.dokuRef.tbl_doku_order_item[] order_itemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_surchargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paid_amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paid_for_msisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long paid_useridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_gatewayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int payment_modeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_receipt_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primary_msisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sess_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_detailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fnameField, value) != true)) {
                    this.fnameField = value;
                    this.RaisePropertyChanged("fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip_address {
            get {
                return this.ip_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_addressField, value) != true)) {
                    this.ip_addressField = value;
                    this.RaisePropertyChanged("ip_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lnameField, value) != true)) {
                    this.lnameField = value;
                    this.RaisePropertyChanged("lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_freight_total {
            get {
                return this.order_freight_totalField;
            }
            set {
                if ((object.ReferenceEquals(this.order_freight_totalField, value) != true)) {
                    this.order_freight_totalField = value;
                    this.RaisePropertyChanged("order_freight_total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public si_bmobile.dokuRef.tbl_doku_order_item[] order_items {
            get {
                return this.order_itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.order_itemsField, value) != true)) {
                    this.order_itemsField = value;
                    this.RaisePropertyChanged("order_items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_surcharge {
            get {
                return this.order_surchargeField;
            }
            set {
                if ((object.ReferenceEquals(this.order_surchargeField, value) != true)) {
                    this.order_surchargeField = value;
                    this.RaisePropertyChanged("order_surcharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paid_amount {
            get {
                return this.paid_amountField;
            }
            set {
                if ((object.ReferenceEquals(this.paid_amountField, value) != true)) {
                    this.paid_amountField = value;
                    this.RaisePropertyChanged("paid_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paid_for_msisdn {
            get {
                return this.paid_for_msisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.paid_for_msisdnField, value) != true)) {
                    this.paid_for_msisdnField = value;
                    this.RaisePropertyChanged("paid_for_msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long paid_userid {
            get {
                return this.paid_useridField;
            }
            set {
                if ((this.paid_useridField.Equals(value) != true)) {
                    this.paid_useridField = value;
                    this.RaisePropertyChanged("paid_userid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_gateway {
            get {
                return this.payment_gatewayField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_gatewayField, value) != true)) {
                    this.payment_gatewayField = value;
                    this.RaisePropertyChanged("payment_gateway");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int payment_mode {
            get {
                return this.payment_modeField;
            }
            set {
                if ((this.payment_modeField.Equals(value) != true)) {
                    this.payment_modeField = value;
                    this.RaisePropertyChanged("payment_mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_receipt_no {
            get {
                return this.payment_receipt_noField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_receipt_noField, value) != true)) {
                    this.payment_receipt_noField = value;
                    this.RaisePropertyChanged("payment_receipt_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_type {
            get {
                return this.payment_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_typeField, value) != true)) {
                    this.payment_typeField = value;
                    this.RaisePropertyChanged("payment_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primary_msisdn {
            get {
                return this.primary_msisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.primary_msisdnField, value) != true)) {
                    this.primary_msisdnField = value;
                    this.RaisePropertyChanged("primary_msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sess_id {
            get {
                return this.sess_idField;
            }
            set {
                if ((object.ReferenceEquals(this.sess_idField, value) != true)) {
                    this.sess_idField = value;
                    this.RaisePropertyChanged("sess_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_details {
            get {
                return this.user_detailsField;
            }
            set {
                if ((object.ReferenceEquals(this.user_detailsField, value) != true)) {
                    this.user_detailsField = value;
                    this.RaisePropertyChanged("user_details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_doku_order_item", Namespace="http://schemas.datacontract.org/2004/07/doku_payment.Models")]
    [System.SerializableAttribute()]
    public partial class tbl_doku_order_item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long order_item_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal product_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long product_qtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long product_shipping_matrix_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purchase_descField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long order_item_id {
            get {
                return this.order_item_idField;
            }
            set {
                if ((this.order_item_idField.Equals(value) != true)) {
                    this.order_item_idField = value;
                    this.RaisePropertyChanged("order_item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.product_nameField, value) != true)) {
                    this.product_nameField = value;
                    this.RaisePropertyChanged("product_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal product_price {
            get {
                return this.product_priceField;
            }
            set {
                if ((this.product_priceField.Equals(value) != true)) {
                    this.product_priceField = value;
                    this.RaisePropertyChanged("product_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long product_qty {
            get {
                return this.product_qtyField;
            }
            set {
                if ((this.product_qtyField.Equals(value) != true)) {
                    this.product_qtyField = value;
                    this.RaisePropertyChanged("product_qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long product_shipping_matrix_id {
            get {
                return this.product_shipping_matrix_idField;
            }
            set {
                if ((this.product_shipping_matrix_idField.Equals(value) != true)) {
                    this.product_shipping_matrix_idField = value;
                    this.RaisePropertyChanged("product_shipping_matrix_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purchase_desc {
            get {
                return this.purchase_descField;
            }
            set {
                if ((object.ReferenceEquals(this.purchase_descField, value) != true)) {
                    this.purchase_descField = value;
                    this.RaisePropertyChanged("purchase_desc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="dokuRef.IdokuService")]
    public interface IdokuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/save_selfcare_order", ReplyAction="http://tempuri.org/IdokuService/save_selfcare_orderResponse")]
        long save_selfcare_order(si_bmobile.dokuRef.PaymentEntModel obj_sc_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/save_doku_order_payment", ReplyAction="http://tempuri.org/IdokuService/save_doku_order_paymentResponse")]
        long save_doku_order_payment(si_bmobile.dokuRef.PaymentEntModel obj_order_pay, long order_id, int site_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/get_doku_order_transactions", ReplyAction="http://tempuri.org/IdokuService/get_doku_order_transactionsResponse")]
        string get_doku_order_transactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/get_doku_order_transactionsBySite", ReplyAction="http://tempuri.org/IdokuService/get_doku_order_transactionsBySiteResponse")]
        string get_doku_order_transactionsBySite(int iSiteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/get_doku_order_transactionsByPurchase", ReplyAction="http://tempuri.org/IdokuService/get_doku_order_transactionsByPurchaseResponse")]
        string get_doku_order_transactionsByPurchase(int iSiteId, string purchase_desc, string sdate, string edate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/get_doku_order_byid", ReplyAction="http://tempuri.org/IdokuService/get_doku_order_byidResponse")]
        string get_doku_order_byid(long order_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/save_temp_order", ReplyAction="http://tempuri.org/IdokuService/save_temp_orderResponse")]
        long save_temp_order(string jstemp_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/get_temp_order_byid", ReplyAction="http://tempuri.org/IdokuService/get_temp_order_byidResponse")]
        string get_temp_order_byid(string session_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/get_shopping_orderby_userid", ReplyAction="http://tempuri.org/IdokuService/get_shopping_orderby_useridResponse")]
        string get_shopping_orderby_userid(long user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/OrderStatus", ReplyAction="http://tempuri.org/IdokuService/OrderStatusResponse")]
        string[] OrderStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/DokuOrderStatus", ReplyAction="http://tempuri.org/IdokuService/DokuOrderStatusResponse")]
        string[] DokuOrderStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/save_selfcare_order_App", ReplyAction="http://tempuri.org/IdokuService/save_selfcare_order_AppResponse")]
        long save_selfcare_order_App(string svcUname, string svcPwd, string sOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/save_doku_order_payment_App", ReplyAction="http://tempuri.org/IdokuService/save_doku_order_payment_AppResponse")]
        long save_doku_order_payment_App(string svcUname, string svcPwd, string sOrderpay, long order_id, int site_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/save_temp_order_App", ReplyAction="http://tempuri.org/IdokuService/save_temp_order_AppResponse")]
        long save_temp_order_App(string svcUname, string svcPwd, string jstemp_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/get_doku_order_byid_App", ReplyAction="http://tempuri.org/IdokuService/get_doku_order_byid_AppResponse")]
        string get_doku_order_byid_App(string svcUname, string svcPwd, long order_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/get_order_transactionsByGateway", ReplyAction="http://tempuri.org/IdokuService/get_order_transactionsByGatewayResponse")]
        string get_order_transactionsByGateway(int iSiteId, string purchase_desc, string sdate, string edate, string spgw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdokuService/save_doku_gui_access", ReplyAction="http://tempuri.org/IdokuService/save_doku_gui_accessResponse")]
        long save_doku_gui_access(string svcUname, string svcPwd, long user_id, string gui_id, string menu_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IdokuServiceChannel : si_bmobile.dokuRef.IdokuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdokuServiceClient : System.ServiceModel.ClientBase<si_bmobile.dokuRef.IdokuService>, si_bmobile.dokuRef.IdokuService {
        
        public IdokuServiceClient() {
        }
        
        public IdokuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdokuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdokuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdokuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long save_selfcare_order(si_bmobile.dokuRef.PaymentEntModel obj_sc_order) {
            return base.Channel.save_selfcare_order(obj_sc_order);
        }
        
        public long save_doku_order_payment(si_bmobile.dokuRef.PaymentEntModel obj_order_pay, long order_id, int site_id) {
            return base.Channel.save_doku_order_payment(obj_order_pay, order_id, site_id);
        }
        
        public string get_doku_order_transactions() {
            return base.Channel.get_doku_order_transactions();
        }
        
        public string get_doku_order_transactionsBySite(int iSiteId) {
            return base.Channel.get_doku_order_transactionsBySite(iSiteId);
        }
        
        public string get_doku_order_transactionsByPurchase(int iSiteId, string purchase_desc, string sdate, string edate) {
            return base.Channel.get_doku_order_transactionsByPurchase(iSiteId, purchase_desc, sdate, edate);
        }
        
        public string get_doku_order_byid(long order_id) {
            return base.Channel.get_doku_order_byid(order_id);
        }
        
        public long save_temp_order(string jstemp_order) {
            return base.Channel.save_temp_order(jstemp_order);
        }
        
        public string get_temp_order_byid(string session_id) {
            return base.Channel.get_temp_order_byid(session_id);
        }
        
        public string get_shopping_orderby_userid(long user_id) {
            return base.Channel.get_shopping_orderby_userid(user_id);
        }
        
        public string[] OrderStatus() {
            return base.Channel.OrderStatus();
        }
        
        public string[] DokuOrderStatus() {
            return base.Channel.DokuOrderStatus();
        }
        
        public long save_selfcare_order_App(string svcUname, string svcPwd, string sOrder) {
            return base.Channel.save_selfcare_order_App(svcUname, svcPwd, sOrder);
        }
        
        public long save_doku_order_payment_App(string svcUname, string svcPwd, string sOrderpay, long order_id, int site_id) {
            return base.Channel.save_doku_order_payment_App(svcUname, svcPwd, sOrderpay, order_id, site_id);
        }
        
        public long save_temp_order_App(string svcUname, string svcPwd, string jstemp_order) {
            return base.Channel.save_temp_order_App(svcUname, svcPwd, jstemp_order);
        }
        
        public string get_doku_order_byid_App(string svcUname, string svcPwd, long order_id) {
            return base.Channel.get_doku_order_byid_App(svcUname, svcPwd, order_id);
        }
        
        public string get_order_transactionsByGateway(int iSiteId, string purchase_desc, string sdate, string edate, string spgw) {
            return base.Channel.get_order_transactionsByGateway(iSiteId, purchase_desc, sdate, edate, spgw);
        }
        
        public long save_doku_gui_access(string svcUname, string svcPwd, long user_id, string gui_id, string menu_id) {
            return base.Channel.save_doku_gui_access(svcUname, svcPwd, user_id, gui_id, menu_id);
        }
    }
}
